//! B7 — project the ranked active-L1 index to `.codeforge/projections/AGENTS.md`,
//! the universal pull surface for **non-Claude agents**.
//!
//! Claude Code sessions get this same ranked index live via the SessionStart
//! recall hook (`codeforge memory context --hook`). Agents that don't run Claude
//! Code hooks (Cursor, aider, Codex CLI, …) discover context by reading an
//! `AGENTS.md` file, so we materialize the index as a real file rather than
//! injecting it. Both surfaces reuse the SAME ranking (`recall::rank`) + lean-index
//! rendering (`recall::render_index`) so they can never drift.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::memory::l1::L1Entry;
use crate::memory::recall;

/// Budget for the projected index — same lean target as SessionStart recall
/// (an index, never a dump; detail pulled on demand via `memory search`).
pub const PROJECTION_MAX_TOKENS: usize = recall::DEFAULT_MAX_TOKENS;

/// Location of the projection under a project dir: `.codeforge/projections/AGENTS.md`.
pub fn projection_path(project_dir: &Path) -> PathBuf {
    project_dir.join("projections").join("AGENTS.md")
}

/// Render the full `AGENTS.md` document from already-ranked entries.
///
/// Prepends a generated-file banner + a short "how to use" preamble, then the same
/// lean ranked-index body the SessionStart recall path emits. `generated_at` is an
/// ISO-8601 stamp (caller supplies — keeps this pure/deterministic in tests).
pub fn render_agents_md(ranked: &[L1Entry], generated_at: &str) -> String {
    let mut out = String::new();
    out.push_str("<!-- GENERATED by `codeforge memory project` — do not edit by hand. -->\n");
    out.push_str(&format!(
        "<!-- refreshed on every `codeforge dream`; generated_at={generated_at} -->\n\n"
    ));
    out.push_str("# AGENTS.md — CodeForge memory\n\n");
    out.push_str(
        "Cross-session engineering knowledge this repo's CodeForge distilled, ranked by \
importance × recency × citation. This is an **index, not a dump** — pull the detail behind \
any line with `codeforge memory search <topic>` (the `<topic>` shown in each entry's \
citation).\n\n",
    );
    out.push_str(&recall::render_index(ranked, "", PROJECTION_MAX_TOKENS));
    out
}

/// Write `content` to `.codeforge/projections/AGENTS.md`, creating the dir if needed.
/// Returns the path written. Atomic-ish: writes then the fs handles the rename-free
/// overwrite (the file is small and single-writer — dream/CLI, never concurrent).
pub fn write_projection(project_dir: &Path, content: &str) -> Result<PathBuf> {
    let path = projection_path(project_dir);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("建立 projections 目錄失敗：{}", parent.display()))?;
    }
    std::fs::write(&path, content)
        .with_context(|| format!("寫入 AGENTS.md 失敗：{}", path.display()))?;
    Ok(path)
}

/// Scan → rank → render → write the projection for `project_dir`'s store. Returns
/// `(path, active_count)`. Used by `codeforge memory project` and the dream refresh.
pub fn regenerate(project_dir: &Path, generated_at: &str) -> Result<(PathBuf, usize)> {
    let store_dir = project_dir.join("store");
    let entries = crate::memory::l1::scan_all(&store_dir)?;
    let ranked = recall::rank(entries);
    let count = ranked.len();
    let md = render_agents_md(&ranked, generated_at);
    let path = write_projection(project_dir, &md)?;
    Ok((path, count))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::l1::{L1Entry, L1Frontmatter, L1Type};
    use std::path::PathBuf;

    fn entry(topic: &str, strength: f32, status: &str, body: &str) -> L1Entry {
        L1Entry {
            frontmatter: L1Frontmatter {
                kind: L1Type::Concept,
                topic: topic.to_string(),
                created: "2026-06-01".to_string(),
                updated: "2026-06-01".to_string(),
                sources: vec![],
                links: vec![],
                refs: 0,
                last_ref: None,
                strength,
                status: status.to_string(),
                origin: "dev".to_string(),
            },
            title: format!("title-{topic}"),
            body: body.to_string(),
            file_path: PathBuf::from(format!("{topic}.md")),
        }
    }

    #[test]
    fn projection_path_is_under_projections() {
        let p = projection_path(Path::new("/x/.codeforge"));
        assert!(p.ends_with("projections/AGENTS.md"));
    }

    #[test]
    fn render_has_banner_preamble_and_ranked_body() {
        let ranked = recall::rank(vec![
            entry("high", 0.9, "active", "# High\n\nimportant lesson body"),
            entry("low", 0.2, "active", "# Low\n\nminor note body"),
            entry("dead", 0.9, "superseded", "# Dead\n\nshould not appear"),
        ]);
        let md = render_agents_md(&ranked, "2026-07-02T00:00:00Z");
        assert!(md.contains("GENERATED by"), "banner present");
        assert!(md.contains("generated_at=2026-07-02T00:00:00Z"));
        assert!(md.contains("memory search"), "pull hint present");
        // ranked body: active topics present, superseded dropped, high before low.
        assert!(md.contains("high") && md.contains("low"));
        assert!(!md.contains("dead"), "superseded entry must be dropped");
        let hi = md.find("high").unwrap();
        let lo = md.find("low").unwrap();
        assert!(hi < lo, "higher strength ranks first");
    }

    #[test]
    fn write_creates_dir_and_file() {
        let tmp = tempfile::tempdir().unwrap();
        let project_dir = tmp.path().join(".codeforge");
        let md = render_agents_md(&[], "2026-07-02T00:00:00Z");
        let path = write_projection(&project_dir, &md).unwrap();
        assert!(path.exists());
        let read = std::fs::read_to_string(&path).unwrap();
        assert!(read.contains("AGENTS.md — CodeForge memory"));
        // empty store → valid file with the "no active L1" note (from render_index).
        assert!(read.contains("尚無 active L1"));
    }

    #[test]
    fn regenerate_reads_store_and_writes_file() {
        let tmp = tempfile::tempdir().unwrap();
        let project_dir = tmp.path().join(".codeforge");
        let concepts = project_dir.join("store").join("concepts");
        std::fs::create_dir_all(&concepts).unwrap();
        std::fs::write(
            concepts.join("x.md"),
            "---\ntype: concept\ntopic: proj-test-topic\ncreated: 2026-06-01\nupdated: 2026-06-01\nsources: []\nlinks: []\nrefs: 0\nlast_ref: null\nstrength: 0.8\nstatus: active\norigin: dev\n---\n\n# Projection Test Lesson\n\nbody of the projection test lesson\n",
        )
        .unwrap();
        let (path, count) = regenerate(&project_dir, "2026-07-02T00:00:00Z").unwrap();
        assert_eq!(count, 1);
        let read = std::fs::read_to_string(&path).unwrap();
        assert!(read.contains("proj-test-topic"), "ranked topic projected");
    }
}
